<?php

namespace AppBundle\Repository;

/**
 * HourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HourRepository extends \Doctrine\ORM\EntityRepository
{
}
